# Gunakan Node.js versi LTS sebagai base image
FROM node:18

# Tentukan working directory di dalam container
WORKDIR /app

# Copy package.json dan package-lock.json ke dalam container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy seluruh kode aplikasi ke dalam working directory
COPY . .

# Expose port (sesuaikan dengan port yang Anda gunakan dalam aplikasi, misalnya 3000)
EXPOSE 3000

# Tentukan environment variable untuk production (optional)
ENV NODE_ENV=production

# Command untuk menjalankan aplikasi
CMD ["node", "index.js"]
