openapi: 3.1.0
info:
  title: Pregnancy Management API
  description: API for managing pregnancy-related data
  version: "1.0.0"
servers:
  - url: http://localhost:3000/api
paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
  /auth/login:
    post:
      summary: Login a user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /auth/protected:
    get:
      summary: Access a protected route
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Access to protected data granted
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Biodata:
      type: object
      properties:
        nama:
          type: string
        ttl:
          type: string
        umur:
          type: integer
        kehamilanKe:
          type: integer
        harapan:
          type: string
        persalinanSecara:
          type: string
        tempatDanPenolong:
          type: string
        biayaDanKendaraan:
          type: string
        tanggalHPHT:
          type: string
          format: date
        tanggalHPL:
          type: string
          format: date
