openapi: 3.0.0
info:
  title: Authentication API
  version: "1.0.0"
  description: API endpoints for user authentication
paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered successfully
        '400':
          description: Bad request when data is invalid
        '500':
          description: Server error

  /auth/login:
    post:
      summary: Login a user and receive a token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
    responses:
    '200':
      description: Login successful
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'Login successful, welcome!'
              data:
                type: object
                properties:
                  token:
                    type: string
                    example: '1 | eyJhbGciOiJIUzI1NiIsInR...'
                  username:
                    type: string
                  userId:
                    type: string
